# Generated by Django 5.2.14 on 2026-05-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookflix", "0002_alter_book_isbn_alter_book_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="goodreads_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
