# Generated by Django 5.2.14 on 2026-05-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookflix", "0003_add_goodreads_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="image_url_l",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="image_url_m",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="image_url_s",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.TextField(),
        ),
    ]
